service: event-sourcing-demo

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs18.x
  memorySize: 128
  timeout: 15
  region: ap-southeast-2
  apiGateway:
    shouldStartNameWithService: true

# Create custom resources with separate CloudFormation templates
resources:
  Resources:
    UsersEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user-events-${opt:stage}
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

functions:
  - Users:
      handler: src/Users.handler
      events:
        - http:
            method: get
            path: users
            cors: true
        - http:
            method: post
            path: users
            cors: true
        - http:
            method: put
            path: users
            cors: true

